# This file will be shipped as part of Crossplane as default MySQL.
apiVersion: apiextensions.crossplane.io/v1alpha1
kind: InfrastructureDefinition
metadata:
  name: mysqls.database.crossplane.io
spec:
  connectionSecretKeys:
    - username
    - password
    - endpoint
  crdSpecTemplate:
    group: database.crossplane.io
    version: v1alpha1
    names:
      kind: MySQL
      listKind: MySQLList
      plural: mysqls
      singular: mysql
    validation:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              engineVersion:
                description: EngineVersion specifies the desired MySQL engine version,
                  e.g. 5.7.
                enum:
                  - "5.6"
                  - "5.7"
                type: string
              storageGB:
                type: integer
---
apiVersion: apiextensions.crossplane.io/v1alpha1
kind: InfrastructurePublication
metadata:
  name: mysqls.database.crossplane.io
spec:
  infrastructureDefinitionRef:
    name: mysqls.database.crossplane.io
