---
apiVersion: compute.azure.crossplane.io/v1alpha3
kind: AKSClusterClass
metadata:
  name: akscluster
  annotations:
    resourceclass.crossplane.io/is-default-class: "true"
specTemplate:
  writeConnectionSecretsToNamespace: crossplane-system
  resourceGroupNameRef:
    name: resourcegroup
  vnetSubnetIDRef:
    name: subnet
  location: $(LOCATION)
  version: "1.15.10"
  nodeCount: 1
  nodeVMSize: Standard_B2s
  dnsNamePrefix: crossplane-aks
  disableRBAC: false
  reclaimPolicy: Delete
  providerRef:
    name: azure-provider
