---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  name: minimalazures.azure.resourcepacks.crossplane.io
spec:
  preserveUnknownFields: true
  group: azure.resourcepacks.crossplane.io
  names:
    kind: MinimalAzure
    listKind: MinimalAzureList
    plural: minimalazures
    singular: minimalazure
  scope: Cluster
  subresources:
    status: {}
  version: v1alpha1
  versions:
    - name: v1alpha1
      served: true
      storage: true
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
