# permissions to do viewer minimalazures.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: minimalazure-viewer-role
rules:
- apiGroups:
  - azure.resourcepacks.crossplane.io
  resources:
  - minimalazures
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - azure.resourcepacks.crossplane.io
  resources:
  - minimalazures/status
  verbs:
  - get
