
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - azure.resourcepacks.crossplane.io
  resources:
  - minimalazures
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - azure.resourcepacks.crossplane.io
  resources:
  - minimalazures/status
  verbs:
  - get
  - patch
  - update
