apiVersion: azure.crossplane.io/v1alpha3
kind: Provider
metadata:
  name: azure-provider
  annotations:
    templatestacks.crossplane.io/deletion-priority: "-1"
spec:
  credentialsSecretRef:
    name: azure-account-creds
    namespace: crossplane-system
    key: credentials