title: "Azure Sample Stack"
overviewShort: |
  Configures an Azure environment with basic networking, security, and
  default resource classes for applications to use.
overview: |
  Configures an Azure environment with basic networking, security,
  and default resource classes that provide a self-service catalog for
  applications to use.
readme: |
  The `Azure Sample Stack` configures the neccesary cloud resources and
  self-service catalog to deploy basic applications like `Wordpress`.

  The managed resources configured by this stack include:
  `ResourceGroup`, `VirtualNetwork`, and `Subnet`.

  This stack offers the following resource classes for applications to
  use: `AKSClusterClass`, `SQLServerClass`, and a `RedisClass`.

  The `Azure Sample Stack` also configures a `Provider` connection
  resource, so the `Azure Provider` can communicate with Azure API.

  [Learn More on GitHub](https://github.com/crossplane/stack-azure-sample)
  to see the complete `kustomize` templates used in this stack and as a
  starting point for building your own stack.
maintainers:
  - name: "Muvaffak Onus"
    email: "monus@upbound.io"
owners:
  - name: "Muvaffak Onus"
    email: "monus@upbound.io"
company: "Crossplane"
category: "Sample Stack"
packageType: "Stack"
keywords:
  - "easy"
  - "azure"
  - "sample"
  - "default"
  - "private network"
website: "https://crossplane.io"
source: "https://github.com/crossplane/stack-azure-sample"
permissionScope: Cluster
dependsOn:
  - crd: 'compositions.apiextensions.crossplane.io'
  - crd: '*.cache.azure.crossplane.io'
  - crd: '*.compute.azure.crossplane.io'
  - crd: '*.database.azure.crossplane.io'
  - crd: '*.network.azure.crossplane.io'
  - crd: '*.azure.crossplane.io'
  - package: 'crossplane/provider-azure'
# License SPDX name: https://spdx.org/licenses/
license: Apache-2.0
