title: "Stack Azure Sample"
readme: |
  An environment with built-in network and classes that let you provision
  resources with minimal node requirements in Azure.
overview: |
  An environment with built-in network and classes that let you provision
  resources with minimal node requirements in Azure.
overviewShort: "Sample stack for Azure."
maintainers:
  - name: "Muvaffak Onus"
    email: "monus@upbound.io"
owners:
  - name: "Muvaffak Onus"
    email: "monus@upbound.io"
company: "Upbound"
category: "Environment Stack"
packageType: "Stack"
keywords:
  - "easy"
  - "azure"
  - "sample"
  - "default"
  - "private network"
website: "upbound.io"
source: "https://github.com/crossplane/stack-azure-sample"
permissionScope: Cluster
dependsOn:
  - crd: '*.cache.azure.crossplane.io/v1beta1'
  - crd: '*.compute.azure.crossplane.io/v1alpha3'
  - crd: '*.database.azure.crossplane.io/v1beta1'
  - crd: '*.network.azure.crossplane.io/v1alpha3'
  - crd: '*.azure.crossplane.io/v1alpha3'
  - package: 'crossplane/provider-azure'
# License SPDX name: https://spdx.org/licenses/
license: Apache-2.0
