
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  name: minimalazures.azure.resourcepacks.crossplane.io
spec:
  group: azure.resourcepacks.crossplane.io
  names:
    kind: MinimalAzure
    plural: minimalazures
  scope: Cluster
  validation:
    openAPIV3Schema:
      description: MinimalAzure is the Schema for the minimalazures API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: MinimalAzureSpec defines the desired state of MinimalAzure
          properties:
            foo:
              description: Foo is an example field of MinimalAzure. Edit MinimalAzure_types.go
                to remove/update
              type: string
          type: object
        status:
          description: MinimalAzureStatus defines the observed state of MinimalAzure
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
